name: Build and Sign Release APK for Bazaar

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # ساخت فایل Release برنامه
    - name: Build APK
      run: ./gradlew assembleRelease

    # تولید کلید رسمی و امضای فایل به صورت 100% تضمینی
    - name: Sign APK with Custom Keystore
      run: |
        keytool -genkeypair -v -keystore release.jks -alias bazaar_key -keyalg RSA -keysize 2048 -validity 10000 -storepass 12345678 -keypass 12345678 -dname "CN=AlaeiService, OU=App, O=Alaei, L=Tehran, ST=Tehran, C=IR"
        
        UNSIGNED_APK=$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)
        
        # پیدا کردن مسیر apksigner در سرور
        APKSIGNER=$(find $ANDROID_HOME/build-tools -name apksigner | sort -V | tail -n 1)
        
        mkdir -p output
        $APKSIGNER sign --ks release.jks --ks-key-alias bazaar_key --ks-pass pass:12345678 --key-pass pass:12345678 --out output/AlaeiService-Market.apk "$UNSIGNED_APK"

    # آپلود فایل نهایی
    - name: Upload Final APK
      uses: actions/upload-artifact@v4
      with:
        name: AlaeiService-Market
        path: output/AlaeiService-Market.apk
